meta_product_name: "CORAIL.ME"
meta_title: "CORAIL.ME - Property sale without commissions"
meta_description: "With Corail, you can enjoy a free platform to find your future house without any commissions on the sale. Say bye to all real estate agencies that take 15% of commission on your house by directly dealing with the owner of your future house. Coral reef is a unique environment for fishes: Corail gives you a unique environment to sell and buy your properties in the best way."
meta_image: "cover.png" # should exist in `app/assets/images/`
